[project]
authors = [
    {name = "Harry Tung", email = "harry@groundlight.ai"},
]
requires-python = "<4.0,>=3.11"
dependencies = [
    "groundlight<1.0.0,>=0.17.1",
    "dvc[s3]<4.0.0,>=3.51.2",
    "framegrab<1.0.0,>=0.6.2",
    "pydantic<3.0.0,>=2.8.2",
]
name = "retaildemo"
version = "0.1.0"
description = ""
readme = "README.md"
